apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-system
spec:
  chart:
    values:
      certmanager:
        install: true
      global:
        hosts:
          domain: >-
            DOMAIN_NAME_HERE
        ingress:
          annotations:
            route.openshift.io/termination: edge
          class: none
      nginx-ingress:
        enabled: false
    version: 6.5.0
