---
# create namespace
kind: Namespace
apiVersion: v1
metadata:
  name: gitlab-system
  labels:
    name: gitlab-system
---
# create operator group
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: gitlab-system
  namespace: gitlab-system
spec:
  targetNamespaces:
  - gitlab-system
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gitlab
  namespace: gitlab-system
spec:
  installPlanApproval: Automatic
  name: gitlab-operator-kubernetes
  source: certified-operators
  sourceNamespace: openshift-marketplace
...

